CREATE TABLE "leads" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"email" varchar(255) NOT NULL,
	"phone" varchar(50) NOT NULL,
	"zip_code" varchar(20) NOT NULL,
	"dog_name" varchar(255) NOT NULL,
	"stranger_reaction" varchar(100),
	"preferred_date" varchar(100),
	"message" text,
	"source" varchar(100) NOT NULL,
	"medium" varchar(100) NOT NULL,
	"campaign" varchar(255),
	"landing_page" text,
	"first_visit" timestamp,
	"utm_content" varchar(255),
	"utm_term" varchar(255),
	"gclid" varchar(255),
	"wbraid" varchar(255),
	"gbraid" varchar(255),
	"msclkid" varchar(255),
	"submitted_from" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"synced_to_crm" varchar(50)
);
