// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/blog-sections/CompactGrid.tsx": () => import("../components/mockups/blog-sections/CompactGrid.tsx"),
  "./components/mockups/blog-sections/Editorial.tsx": () => import("../components/mockups/blog-sections/Editorial.tsx"),
  "./components/mockups/blog-sections/FeaturedSplit.tsx": () => import("../components/mockups/blog-sections/FeaturedSplit.tsx"),
  "./components/mockups/blog-sections/StoryCarousel.tsx": () => import("../components/mockups/blog-sections/StoryCarousel.tsx"),
  "./components/mockups/boca-landing/BocaHero.tsx": () => import("../components/mockups/boca-landing/BocaHero.tsx"),
  "./components/mockups/boca-landing/BocaHeroAlt.tsx": () => import("../components/mockups/boca-landing/BocaHeroAlt.tsx"),
  "./components/mockups/boca-landing/Current.tsx": () => import("../components/mockups/boca-landing/Current.tsx"),
  "./components/mockups/fan-carousel/CardFanCarousel.tsx": () => import("../components/mockups/fan-carousel/CardFanCarousel.tsx"),
  "./components/mockups/fan-carousel/Demo.tsx": () => import("../components/mockups/fan-carousel/Demo.tsx"),
  "./components/mockups/service-cards/BoldColor.tsx": () => import("../components/mockups/service-cards/BoldColor.tsx"),
  "./components/mockups/service-cards/Cinematic.tsx": () => import("../components/mockups/service-cards/Cinematic.tsx"),
  "./components/mockups/service-cards/Frosted.tsx": () => import("../components/mockups/service-cards/Frosted.tsx"),
  "./components/mockups/service-cards/Outlined.tsx": () => import("../components/mockups/service-cards/Outlined.tsx"),
  "./components/mockups/woof-hero/HeroBlended.tsx": () => import("../components/mockups/woof-hero/HeroBlended.tsx"),
  "./components/mockups/woof-hero/HeroProgramCards.tsx": () => import("../components/mockups/woof-hero/HeroProgramCards.tsx"),
  "./components/mockups/woof-hero/HeroProgramCardsV2.tsx": () => import("../components/mockups/woof-hero/HeroProgramCardsV2.tsx"),
  "./components/mockups/woof-hero/WoofHero.tsx": () => import("../components/mockups/woof-hero/WoofHero.tsx"),
  "./components/mockups/woof-hero/WoofHeroV1.tsx": () => import("../components/mockups/woof-hero/WoofHeroV1.tsx"),
  "./components/mockups/woof-hero/WoofHeroV2.tsx": () => import("../components/mockups/woof-hero/WoofHeroV2.tsx"),
  "./components/mockups/templates/WarmAPIContactPage-dGsGJC/App.tsx": () => import("../components/mockups/templates/WarmAPIContactPage-dGsGJC/App.tsx")
};
